name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          mkdir -p test-results
          npm test > test-results/results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

  deploy:
    needs: test
    runs-on: self-hosted  # Self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download test results artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./downloaded-artifacts/

      - name: Display test results
        run: cat ./downloaded-artifacts/results.txt

      - name: Deploy Application
        run: |
          echo "Deploying Node.js Application..."
          pm2 stop my-app || true
          pm2 start app.js --name my-app
