name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on GitHub-hosted runner (Ubuntu)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          mkdir -p test-results
          npm test > test-results/results.txt

      - name: Upload test results (Updated to v4)
        uses: actions/upload-artifact@v4  # 👈 UPDATED TO V4
        with:
          name: test-results
          path: test-results/

  deploy:
    needs: test
    runs-on: [self-hosted, macos]  # Ensures it runs only on your macOS self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download test results artifact (Updated to v4)
        uses: actions/download-artifact@v4  # 👈 UPDATED TO V4
        with:
          name: test-results
          path: ./downloaded-artifacts/

      - name: Display test results
        run: cat ./downloaded-artifacts/results.txt

      - name: Ensure Node.js is Installed (macOS)
        run: |
          if ! command -v node &> /dev/null; then
            echo "Node.js not found. Installing..."
            brew install node
          else
            echo "Node.js already installed"
          fi
        shell: bash

      - name: Ensure PM2 is Installed (macOS)
        run: |
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found. Installing..."
            npm install -g pm2
          else
            echo "PM2 already installed"
          fi
        shell: bash

      - name: Deploy Application
        run: |
          echo "Deploying Node.js Application..."
          pm2 stop my-app || true
          pm2 start app.js --name my-app
